fixtures:
  repositories:
    xinetd:
      repo: 'https://www.github.com/puppetlabs/puppetlabs-xinetd'
    concat:
      repo: 'https://www.github.com/puppetlabs/puppetlabs-concat'
    stdlib:
      repo: 'https://www.github.com/puppetlabs/puppetlabs-stdlib'
  symlinks:
    "rsync": "#{source_dir}"
